.TH "c_interface" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c_interface \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfile_exists\fP"
.br
.ti -1c
.RI "def \fBerror_die\fP"
.br
.ti -1c
.RI "def \fBprint_usage\fP"
.br
.ti -1c
.RI "def \fBchar_range\fP"
.br
.ti -1c
.RI "def \fBmain\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBobjs\fP = ['BIN', 'SECT', 'FUNC', 'CFG', 'LOOP', 'BBL', 'INSN', 'SYM', 'FLOW']"
.br
.ti -1c
.RI "dictionary \fBother\fP = {}"
.br
.ti -1c
.RI "dictionary \fBremove\fP = {}"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def \fBc_interface\&.char_range\fP (c1, c2)"
.PP
Definition at line 39 of file c_interface\&.py\&.
.SS "def \fBc_interface\&.error_die\fP (msg = \fC''\fP)"
.PP
Definition at line 30 of file c_interface\&.py\&.
.SS "def \fBc_interface\&.file_exists\fP (f)"
.PP
Definition at line 25 of file c_interface\&.py\&.
.SS "def \fBc_interface\&.main\fP ()"
.PP
Definition at line 43 of file c_interface\&.py\&.
.SS "def \fBc_interface\&.print_usage\fP (msg = \fC''\fP)"
.PP
Definition at line 35 of file c_interface\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "list \fBc_interface::objs\fP = ['BIN', 'SECT', 'FUNC', 'CFG', 'LOOP', 'BBL', 'INSN', 'SYM', 'FLOW']"
.PP
Definition at line 7 of file c_interface\&.py\&.
.SS "dictionary \fBc_interface::other\fP = {}"
.PP
Definition at line 8 of file c_interface\&.py\&.
.SS "dictionary \fBc_interface::remove\fP = {}"
.PP
Definition at line 20 of file c_interface\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
