.TH "c_interface.py" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c_interface.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBc_interface\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBc_interface\&.file_exists\fP"
.br
.ti -1c
.RI "def \fBc_interface\&.error_die\fP"
.br
.ti -1c
.RI "def \fBc_interface\&.print_usage\fP"
.br
.ti -1c
.RI "def \fBc_interface\&.char_range\fP"
.br
.ti -1c
.RI "def \fBc_interface\&.main\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "list \fBc_interface\&.objs\fP = ['BIN', 'SECT', 'FUNC', 'CFG', 'LOOP', 'BBL', 'INSN', 'SYM', 'FLOW']"
.br
.ti -1c
.RI "dictionary \fBc_interface\&.other\fP = {}"
.br
.ti -1c
.RI "dictionary \fBc_interface\&.remove\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
