.TH "EPAX::Elf::ElfSymbolTable" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::ElfSymbolTable \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::SymbolTable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElfSymbolTable\fP (\fBBaseBinary\fP *b, uint64_t o, uint64_t fs, uint64_t ma, uint64_t ms, uint32_t i, std::string n, \fBElfStringTable\fP *st)"
.br
.ti -1c
.RI "\fB~ElfSymbolTable\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP (std::ostream &stream=std::cout)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 236 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::ElfSymbolTable::ElfSymbolTable\fP (\fBBaseBinary\fP *b, uint64_to, uint64_tfs, uint64_tma, uint64_tms, uint32_ti, std::stringn, \fBElfStringTable\fP *st)"
.PP
Definition at line 649 of file ElfBinary\&.cpp\&.
.SS "\fBEPAX::Elf::ElfSymbolTable::~ElfSymbolTable\fP ()\fC [inline]\fP"
.PP
Definition at line 242 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBEPAX::Elf::ElfSymbolTable::print\fP (std::ostream &stream = \fCstd::cout\fP)\fC [virtual]\fP"
.PP
Implements \fBEPAX::SymbolTable\fP\&.
.PP
Definition at line 518 of file ElfBinary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
