.TH "EPAX::Elf::ElfBinary64" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::ElfBinary64 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::Elf::ElfBinary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElfBinary64\fP (std::string n)"
.br
.ti -1c
.RI "virtual \fB~ElfBinary64\fP ()"
.br
.ti -1c
.RI "\fBBinaryFormat\fP \fBgetFormat\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::ElfBinary64::ElfBinary64\fP (std::stringn)"
.PP
Definition at line 130 of file ElfBinary\&.cpp\&.
.SS "virtual \fBEPAX::Elf::ElfBinary64::~ElfBinary64\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 95 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBinaryFormat\fP \fBEPAX::Elf::ElfBinary64::getFormat\fP ()\fC [inline, virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfBinary\fP\&.
.PP
Definition at line 97 of file ElfBinary\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
