.TH "EPAX::Elf::ProgramHeader64" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::ProgramHeader64 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::Elf::ProgramHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgramHeader64\fP (\fBBaseBinary\fP *b, uint64_t o, uint64_t s, uint32_t i)"
.br
.ti -1c
.RI "virtual \fB~ProgramHeader64\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetVaddr\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetPaddr\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFSize\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetMSize\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSegmentType\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFlags\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetAlignment\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFOffset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 355 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::ProgramHeader64::ProgramHeader64\fP (\fBBaseBinary\fP *b, uint64_to, uint64_ts, uint32_ti)"
.PP
Definition at line 891 of file ElfBinary\&.cpp\&.
.SS "virtual \fBEPAX::Elf::ProgramHeader64::~ProgramHeader64\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 358 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t \fBEPAX::Elf::ProgramHeader64::getAlignment\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 942 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getFlags\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 934 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getFOffset\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 958 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getFSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 918 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getMSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 926 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getPaddr\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 910 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::ProgramHeader64::getSegmentType\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 950 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader64::getVaddr\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 902 of file ElfBinary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
