.TH "EPAX::Elf::ElfSymbol64" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::ElfSymbol64 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::Elf::ElfSymbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElfSymbol64\fP (\fBBaseBinary\fP *b, uint64_t o, uint32_t i)"
.br
.ti -1c
.RI "virtual \fB~ElfSymbol64\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetNameIndex\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetValue\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSection\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSize\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetType\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetBinding\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetVisibility\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 208 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::ElfSymbol64::ElfSymbol64\fP (\fBBaseBinary\fP *b, uint64_to, uint32_ti)"
.PP
Definition at line 549 of file ElfBinary\&.cpp\&.
.SS "virtual \fBEPAX::Elf::ElfSymbol64::~ElfSymbol64\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 211 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t \fBEPAX::Elf::ElfSymbol64::getBinding\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 600 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ElfSymbol64::getNameIndex\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 560 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::ElfSymbol64::getSection\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 584 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::ElfSymbol64::getSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 576 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::ElfSymbol64::getType\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 592 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ElfSymbol64::getValue\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 568 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ElfSymbol64::getVisibility\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ElfSymbol\fP\&.
.PP
Definition at line 608 of file ElfBinary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
