.TH "EPAX::Elf::FileHeader32" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::FileHeader32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::Elf::FileHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileHeader32\fP (\fBBaseBinary\fP *b, uint64_t o)"
.br
.ti -1c
.RI "virtual \fB~FileHeader32\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetStartAddr\fP ()"
.br
.ti -1c
.RI "bool \fBverify\fP ()"
.br
.ti -1c
.RI "bool \fBisARM\fP ()"
.br
.ti -1c
.RI "void \fBdescribe\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSectionCount\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetSecTableOffset\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetShdrSize\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetShdrStringIndex\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSegmentCount\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetSegTableOffset\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetPhdrSize\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetFileType\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::FileHeader32::FileHeader32\fP (\fBBaseBinary\fP *b, uint64_to)"
.PP
Definition at line 397 of file ElfBinary\&.cpp\&.
.SS "virtual \fBEPAX::Elf::FileHeader32::~FileHeader32\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 131 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBEPAX::Elf::FileHeader32::describe\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 484 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getFileType\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 389 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getPhdrSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 357 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::FileHeader32::getSecTableOffset\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 333 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getSectionCount\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 373 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getSegmentCount\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 381 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::FileHeader32::getSegTableOffset\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 349 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getShdrSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 341 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::FileHeader32::getShdrStringIndex\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 365 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::FileHeader32::getStartAddr\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 411 of file ElfBinary\&.cpp\&.
.SS "bool \fBEPAX::Elf::FileHeader32::isARM\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 447 of file ElfBinary\&.cpp\&.
.SS "bool \fBEPAX::Elf::FileHeader32::verify\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::FileHeader\fP\&.
.PP
Definition at line 419 of file ElfBinary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
