.TH "EPAX::MachO::MachOBinary64" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::MachO::MachOBinary64 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MachOBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::MachO::MachOBinary\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMachOBinary64\fP (std::string n)"
.br
.ti -1c
.RI "virtual \fB~MachOBinary64\fP ()"
.br
.ti -1c
.RI "\fBBinaryFormat\fP \fBgetFormat\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 77 of file MachOBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::MachO::MachOBinary64::MachOBinary64\fP (std::stringn)"
.PP
Definition at line 77 of file MachOBinary\&.cpp\&.
.SS "virtual \fBEPAX::MachO::MachOBinary64::~MachOBinary64\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 80 of file MachOBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBBinaryFormat\fP \fBEPAX::MachO::MachOBinary64::getFormat\fP ()\fC [inline, virtual]\fP"
.PP
Implements \fBEPAX::MachO::MachOBinary\fP\&.
.PP
Definition at line 82 of file MachOBinary\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
