.TH "EPAXExport" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAXExport \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EPAXCommonInternal\&.hpp>\fP
.PP
Inherited by \fBEPAX::BasicBlock\fP, \fBEPAX::Binary\fP, \fBEPAX::ControlFlow\fP, \fBEPAX::Function\fP, \fBEPAX::Instruction\fP, \fBEPAX::Loop\fP, \fBEPAX::Section\fP, and \fBEPAX::Symbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEPAXExport\fP (\fBEPAXExportClass\fP cls)"
.br
.ti -1c
.RI "virtual \fB~EPAXExport\fP ()"
.br
.ti -1c
.RI "\fBEPAXExportClass\fP \fBgetClass\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEPAXExportClass\fP \fBexpclass\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 112 of file EPAXCommonInternal\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAXExport::EPAXExport\fP (\fBEPAXExportClass\fPcls)\fC [inline]\fP"
.PP
Definition at line 116 of file EPAXCommonInternal\&.hpp\&.
.SS "virtual \fBEPAXExport::~EPAXExport\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 117 of file EPAXCommonInternal\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBEPAXExportClass\fP \fBEPAXExport::getClass\fP ()\fC [inline]\fP"
.PP
Definition at line 119 of file EPAXCommonInternal\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEPAXExportClass\fP \fBEPAXExport::expclass\fP\fC [protected]\fP"
.PP
Definition at line 114 of file EPAXCommonInternal\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
