.TH "EPAX::SymbolBase" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::SymbolBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseClass\&.hpp>\fP
.PP
Inherited by \fBEPAX::Function\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymbolBase\fP (\fBSymbol\fP *s)"
.br
.ti -1c
.RI "virtual \fB~SymbolBase\fP ()"
.br
.ti -1c
.RI "\fBSymbol\fP * \fBgetSymbol\fP ()"
.br
.ti -1c
.RI "void \fBsetSymbol\fP (\fBSymbol\fP *s)"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 80 of file BaseClass\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::SymbolBase::SymbolBase\fP (\fBSymbol\fP *s)\fC [inline]\fP"
.PP
Definition at line 84 of file BaseClass\&.hpp\&.
.SS "virtual \fBEPAX::SymbolBase::~SymbolBase\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 86 of file BaseClass\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string \fBEPAX::SymbolBase::getName\fP ()"
.PP
Definition at line 39 of file BaseClass\&.cpp\&.
.SS "\fBSymbol\fP* \fBEPAX::SymbolBase::getSymbol\fP ()\fC [inline]\fP"
.PP
Definition at line 88 of file BaseClass\&.hpp\&.
.SS "void \fBEPAX::SymbolBase::setSymbol\fP (\fBSymbol\fP *s)\fC [inline]\fP"
.PP
Definition at line 89 of file BaseClass\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
