.TH "EPAX::InputFile" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::InputFile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InputFile\&.hpp>\fP
.PP
Inherits \fBEPAX::NameBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputFile\fP (std::string n)"
.br
.ti -1c
.RI "virtual \fB~InputFile\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetBytes\fP (uint64_t offset, uint64_t size, \fBrawbyte_t\fP *buffer)"
.br
.ti -1c
.RI "uint64_t \fBgetFileSize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file InputFile\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::InputFile::InputFile\fP (std::stringn)"
.PP
Definition at line 30 of file InputFile\&.cpp\&.
.SS "\fBEPAX::InputFile::~InputFile\fP ()\fC [virtual]\fP"
.PP
Definition at line 38 of file InputFile\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint64_t \fBEPAX::InputFile::getBytes\fP (uint64_toffset, uint64_tsize, \fBrawbyte_t\fP *buffer)"
.PP
Definition at line 54 of file InputFile\&.cpp\&.
.SS "uint64_t \fBEPAX::InputFile::getFileSize\fP ()"
.PP
Definition at line 44 of file InputFile\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
