.TH "EPAX::NameBase" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::NameBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BaseClass\&.hpp>\fP
.PP
Inherited by \fBEPAX::BaseBinary\fP, \fBEPAX::Elf::SectionHeader\fP, \fBEPAX::InputFile\fP, \fBEPAX::Section\fP, and \fBEPAX::Symbol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameBase\fP (std::string n)"
.br
.ti -1c
.RI "\fBNameBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~NameBase\fP ()"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file BaseClass\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::NameBase::NameBase\fP (std::stringn)\fC [inline]\fP"
.PP
Definition at line 112 of file BaseClass\&.hpp\&.
.SS "\fBEPAX::NameBase::NameBase\fP ()\fC [inline]\fP"
.PP
Definition at line 113 of file BaseClass\&.hpp\&.
.SS "virtual \fBEPAX::NameBase::~NameBase\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 114 of file BaseClass\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string \fBEPAX::NameBase::getName\fP ()\fC [inline]\fP"
.PP
Definition at line 116 of file BaseClass\&.hpp\&.
.SS "void \fBEPAX::NameBase::setName\fP (std::stringn)\fC [inline]\fP"
.PP
Definition at line 117 of file BaseClass\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
