.TH "EPAX::Elf::ProgramHeader32" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::Elf::ProgramHeader32 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ElfBinary\&.hpp>\fP
.PP
Inherits \fBEPAX::Elf::ProgramHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgramHeader32\fP (\fBBaseBinary\fP *b, uint64_t o, uint64_t s, uint32_t i)"
.br
.ti -1c
.RI "virtual \fB~ProgramHeader32\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetVaddr\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetPaddr\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFSize\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetMSize\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetSegmentType\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFlags\fP ()"
.br
.ti -1c
.RI "uint32_t \fBgetAlignment\fP ()"
.br
.ti -1c
.RI "uint64_t \fBgetFOffset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 340 of file ElfBinary\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBEPAX::Elf::ProgramHeader32::ProgramHeader32\fP (\fBBaseBinary\fP *b, uint64_to, uint64_ts, uint32_ti)"
.PP
Definition at line 884 of file ElfBinary\&.cpp\&.
.SS "virtual \fBEPAX::Elf::ProgramHeader32::~ProgramHeader32\fP ()\fC [inline, virtual]\fP"
.PP
Definition at line 343 of file ElfBinary\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "uint32_t \fBEPAX::Elf::ProgramHeader32::getAlignment\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 938 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getFlags\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 930 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getFOffset\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 954 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getFSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 914 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getMSize\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 922 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getPaddr\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 906 of file ElfBinary\&.cpp\&.
.SS "uint32_t \fBEPAX::Elf::ProgramHeader32::getSegmentType\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 946 of file ElfBinary\&.cpp\&.
.SS "uint64_t \fBEPAX::Elf::ProgramHeader32::getVaddr\fP ()\fC [virtual]\fP"
.PP
Implements \fBEPAX::Elf::ProgramHeader\fP\&.
.PP
Definition at line 898 of file ElfBinary\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
