.TH "EPAX::MachO" 3 "Fri Feb 7 2014" "Version 0.01" "EPAXDeveloperGuide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EPAX::MachO \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMachOBinary\fP"
.br
.ti -1c
.RI "class \fBMachOBinary32\fP"
.br
.ti -1c
.RI "class \fBMachOBinary64\fP"
.br
.ti -1c
.RI "class \fBMachHeader\fP"
.br
.ti -1c
.RI "class \fBMachHeader32\fP"
.br
.ti -1c
.RI "class \fBMachHeader64\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EPAXDeveloperGuide from the source code\&.
